#!/usr/local/bin/bash
export VOLUME=${1:-/tmp/volume1/}
export PORT=${PORT:-3001}
export HOST=${HOST:-$(hostname)}
export TYPE=volume
uwsgi --http :$PORT --wsgi-file src/server.py --callable volume --master --processes 4

